# Generated by Django 6.0.4 on 2026-04-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='dashboard.employee'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='dashboard.financialoperation'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['is_active', 'role'], name='dashboard_e_is_acti_56e0f8_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['full_name'], name='dashboard_e_full_na_64b4bd_idx'),
        ),
        migrations.AddIndex(
            model_name='financialoperation',
            index=models.Index(fields=['occurred_on', 'created_at'], name='dashboard_f_occurre_8bb5c0_idx'),
        ),
        migrations.AddIndex(
            model_name='financialoperation',
            index=models.Index(fields=['kind', 'occurred_on'], name='dashboard_f_kind_6cb80b_idx'),
        ),
        migrations.AddIndex(
            model_name='financialoperation',
            index=models.Index(fields=['category', 'occurred_on'], name='dashboard_f_catego_4ae5bc_idx'),
        ),
        migrations.AddIndex(
            model_name='financialoperation',
            index=models.Index(fields=['created_by', 'occurred_on'], name='dashboard_f_created_427fb4_idx'),
        ),
        migrations.AddIndex(
            model_name='financialoperation',
            index=models.Index(fields=['employee', 'occurred_on'], name='dashboard_f_employe_ee922d_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialoperation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='financial_operation_amount_gt_zero'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action', 'created_at'], name='dashboard_a_action_0241ec_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='dashboard_a_entity__f335cb_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['operation', 'created_at'], name='dashboard_a_operati_1d2d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['employee', 'created_at'], name='dashboard_a_employe_60f48e_idx'),
        ),
    ]
