# Generated by Django 6.0.4 on 2026-04-13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_enhance_er_relations'),
        ('accounts', '0003_customuser_user_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sku', models.CharField(max_length=40, unique=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [
                    models.Index(fields=['is_active', 'name'], name='dashboard_p_is_acti_df7258_idx'),
                    models.Index(fields=['sku'], name='dashboard_p_sku_22a43e_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='dashboard_s_is_acti_174205_idx')],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_on', models.DateField()),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='dashboard.employee')),
            ],
            options={
                'ordering': ['-occurred_on', '-created_at'],
                'indexes': [
                    models.Index(fields=['occurred_on', 'created_at'], name='dashboard_s_occurre_97ab20_idx'),
                    models.Index(fields=['created_by', 'occurred_on'], name='dashboard_s_created_fd018f_idx'),
                    models.Index(fields=['employee', 'occurred_on'], name='dashboard_s_employe_4f5fc6_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='dashboard.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.sale')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='dashboard.service')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [
                    models.Index(fields=['sale', 'id'], name='dashboard_s_sale_id_343635_idx'),
                    models.Index(fields=['product'], name='dashboard_s_product_02b9d9_idx'),
                    models.Index(fields=['service'], name='dashboard_s_service_c8ad73_idx'),
                ],
                'constraints': [
                    models.CheckConstraint(condition=Q(('quantity__gt', 0)), name='sale_item_quantity_gt_zero'),
                    models.CheckConstraint(condition=Q(('unit_price__gt', 0)), name='sale_item_unit_price_gt_zero'),
                    models.CheckConstraint(condition=Q(('subtotal__gt', 0)), name='sale_item_subtotal_gt_zero'),
                ],
            },
        ),
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS subscriptions_stripecustomer;',
            reverse_sql='SELECT 1;',
        ),
    ]
