# Generated by Django 6.0.4 on 2026-04-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('gerente', 'Gerente'), ('empleado', 'Empleado')], default='empleado', max_length=20),
        ),
    ]
