# Generated by Django 6.0.4 on 2026-04-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(
                choices=[('cliente', 'Cliente'), ('colaborador', 'Colaborador')],
                default='cliente',
                max_length=20,
            ),
        ),
    ]
